/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIArea: typeof import('./src/components/AIArea/index.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    MatchArea: typeof import('./src/components/MatchArea/index.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheMatchs: typeof import('./src/components/MatchArea/TheMatchs.vue')['default']
    TheSearch: typeof import('./src/components/MatchArea/TheSearch.vue')['default']
  }
}
